### ISSUE TITLE
[오류] 레시피가 잘못 됐잖슴까! 

### ISSUE THREAD

**Issue by mome0320** [Mcdonaldo/bigmac-song#2]
특별한 소스 양상추라는 건 읎어요!

특별한 소스 다음에 양상추 이렇게 분리해야하지 않나 싶습니다.

이건 빅맥 레시피의 명백한 오류잖아요!
이건 빅맥에 대한 모욕입니다. 

커밋 형식과 태그 수정 바랍니다.

**Comment by ghostdeleted** [comment]
@wonderlandpark

**Comment by wonderlandpark** [comment]
거부합니다 특별한 소스가 빠진 양상추는 먹을 수 없으니 재료가 될 수 없습니다.

**Comment by wonderlandpark** [comment]
@sannoob 님이 양상추만 먹는 장면을 인증하신다면 수락하겠습니다.

**Comment by ghostdeleted** [comment]
저 그냥 양상추 씹어먹는데

**Comment by wonderlandpark** [comment]
이번 실험에서 우린 특별한 소스 없이 양상추를 먹을 수 있는지 고민해보기로 했다

**Comment by wonderlandpark** [comment]
빠빰빠라빰~

**Comment by kijk2869** [comment]
애초에 **참깨빵 위에** 부터가 틀렸는데
